{% set name = "jsonnet" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d6eff8c17e146dccd244eda45317577cd5e264ce8d5d0676f1f36afdc01307e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - _jsonnet

about:
  home: http://github.com/google/jsonnet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for Jsonnet - The data templating language

extra:
  recipe-maintainers:
    - nelson-liu
    - michamucha
    - synapticarbors
